feat: #49 point_details curd 구현
nhnacademy-be5-T3Team/bookstore-api pull request #137
Opened 2024-05-03 01:25 UTC by hydrationn

2024-05-07 04:21 UTC, Yujin-nKim commented on src/main/java/com/t3t/bookstoreapi/member/model/entity/Member.java
> +@Setter
entity에서 setter를 빼고 변경해야할 필드에 대해서만 함수를 만들어 사용하는 편은 어떨까요?

블로그 글이긴 하지만 다음 글 참고하시면 좋을것 같습니다.
https://hstory0208.tistory.com/entry/JPA-Entitiy%EC%97%90%EC%84%9C-%EC%99%9C-Setter%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EB%9D%BC%EA%B3%A0-%ED%95%A0%EA%B9%8C

2024-05-07 04:21 UTC, Yujin-nKim commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/PointController.java
> + * 회원 보유 포인트(point)를 최산화한다.
오타있습니다!

2024-05-07 05:57 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/AdminPointDetailController.java
> +    @GetMapping("/pointDetails/admin/{memberId}")
URI 상에 권한을 표현하는 부분이 중간에 배치되는것보다는, 가장 앞에 배치하면 URI 패턴 기반으로 인가 처리 할 때 더 편할 것 같아요!

2024-05-07 06:24 UTC, woody35545 requested changes

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/PointController.java
> +    @PutMapping("/point/update/{memberId}")
http put 메서드가 갱신하는 행위를 표현하고 있기 때문에 URI 상에 update 는 제거하면 좋을 것 같아요!

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/PointController.java
> +    @PutMapping("/point/update/{memberId}")
회원 정보 중 보유 포인트만 갱신하는 API 라면, PUT 보다는 PATCH 로 하면 어떨까요??

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/UserPointDetailController.java
> +    @GetMapping("/pointDetails/{members}")
URI를 "/members/{memberId}/point-details" 라고 하면 어떨까요?

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/UserPointDetailController.java
> +    public ResponseEntity<BaseResponse<List<PointDetailResponse>>> getPointDetailList(@RequestHeader(name = "memberId") @PathVariable("memberId") Long memberId){
요청 URI의 PathVariable 에는 members로 되어있는데 파라미터 바인딩하는 부분에서는 @PathVariable("memberId") 로 되어 있어요!

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/filter/PointDetailAuthFilter.java
> +public class PointDetailAuthFilter implements Filter {
PointDetail 에서 별도의 AuthFilter 를 구현한 이유가 있나요??

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/service/AdminPointDetailService.java
> +    public PointDetailResponse createPointDetail(Long adminId, Long memberId, CreatePointDetailRequest request) {
CreatePointDetailRequest 객체에는 Validation 처리를 위한 어노테이션이 선언되어 있는데, 컨트롤러에서 받을 때 @Valid 가 생략된 것 같아요!

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/wrapper/RequestWrapper.java
> +    private final Map<String, String> customHeader;
PointDetail 패키지 내에 RequestWrapper 가 새로 정의된 이유가 있을까요??

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/service/PointService.java
> +        memberRepository.save(member);
엔티티는 변경감지가 일어나니까 별도로 save를 호출하지 않아도 될 것 같아요!

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/model/entity/PointDetail.java
> +@Setter
엔티티에서는 가급적이면 Setter 를 쓰지 않는게 좋을 것 같아요!

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/exception/PointDetailNotFoundException.java
> +public class PointDetailNotFoundException extends RuntimeException{
PointDetailNotFoundException 이 발생했을 때 처리하는 부분이 구현되어 있을까요??

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/AdminPointDetailController.java
> +    @GetMapping("/pointDetails/admin/{memberId}")
특정 회원의 포인트 상세 내역을 조회하는 API 이니까,
요청 URI 를 /admin/members/{memberId}/point-details 로 바꾸면 어떨까요??

2024-05-07 06:24 UTC, woody35545 commented on src/main/java/com/t3t/bookstoreapi/pointdetail/repository/PointDetailRepository.java
> +    PointDetail findByMemberIdAndPointDetailType(Long memberId, String pointDetailType);
반환값이 Nullable 하니까 Optional 로 감싸서 반환하면 좋을 것 같아요!

2024-05-07 06:32 UTC, woody35545 requested changes
전체적으로 URI를 Restful 하게 수정하면 좋을 것 같아요!

2024-05-07 11:22 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/member/model/entity/Member.java
> +@Setter
update로 함수 만들어서 수정했습니다!

2024-05-07 11:24 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/PointController.java
> + * 회원 보유 포인트(point)를 최산화한다.
해당 클래스는 로직 수정 과정에서 삭제되었습니다ㅏ~~

2024-05-07 11:25 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/AdminPointDetailController.java
> +    @GetMapping("/pointDetails/admin/{memberId}")
수정 완료입니다!!

2024-05-07 11:25 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/PointController.java
> +    @PutMapping("/point/update/{memberId}")
제거 완료입니다!!

2024-05-07 11:29 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/UserPointDetailController.java
> +    @GetMapping("/pointDetails/{members}")
수정 완료입니다!!

2024-05-07 11:30 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/service/AdminPointDetailService.java
> +    public PointDetailResponse createPointDetail(Long adminId, Long memberId, CreatePointDetailRequest request) {
수정 완료입니다!!

2024-05-07 11:36 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/model/entity/PointDetail.java
> +@Setter
수정 완료입니다!!

2024-05-07 11:38 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/repository/PointDetailRepository.java
> +    PointDetail findByMemberIdAndPointDetailType(Long memberId, String pointDetailType);
수정 완료입니다!!

2024-05-07 11:39 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/controller/AdminPointDetailController.java
> +    @GetMapping("/pointDetails/admin/{memberId}")
수정 완료입니다!!

2024-05-07 11:42 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/filter/PointDetailAuthFilter.java
> +public class PointDetailAuthFilter implements Filter {
관리자 인증 로직 추가에 대한 피드백 과정에서 잘못 이해해서 구현해 버린 것입니다.. 현재 해당 클래스는 삭제되었습니다!

2024-05-07 11:44 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/service/PointService.java
> +        memberRepository.save(member);
해당 클래스는 수정 과정에서 삭제되었습니다! AdminService create 부분에서 포인트 내역 생성 후, 바로 member table의 point가 업데이트 되도록 수정했습니다!

2024-05-07 11:45 UTC, hydrationn commented on src/main/java/com/t3t/bookstoreapi/pointdetail/wrapper/RequestWrapper.java
> +    private final Map<String, String> customHeader;
이전에 AuthFilterd에서 필요한 클래스였습니다.. 지금은 삭제되었습니다!

2024-05-08 01:23 UTC, woody35545 approved these changes
고생하셨습니다!

2024-05-09 13:54 UTC, joohyun1996 approved these changes
수고하셨습니다

2024-05-12 18:40 UTC, merged